inffile=%SystemRoot%\system32\NOTEPAD.EXE %1
inifile=%SystemRoot%\system32\NOTEPAD.EXE %1
Microsoft.PowerShellData.1="C:\Windows\System32\notepad.exe" "%1"
Microsoft.PowerShellModule.1="C:\Windows\System32\notepad.exe" "%1"
Microsoft.PowerShellScript.1="C:\Windows\System32\notepad.exe" "%1"
scriptletfile="C:\Windows\System32\NOTEPAD.EXE" "%1"
Windows.CompositeFont="%SystemRoot%\System32\notepad.exe" "%1"
docxfile="%ProgramFiles%\Windows NT\Accessories\WORDPAD.EXE" "%1"
odtfile="%ProgramFiles%\Windows NT\Accessories\WORDPAD.EXE" "%1"
rtffile="%ProgramFiles%\Windows NT\Accessories\WORDPAD.EXE" "%1"
textfile="%ProgramFiles%\Windows NT\Accessories\WORDPAD.EXE" "%1"
Wordpad.Document.1="%ProgramFiles%\Windows NT\Accessories\WORDPAD.EXE" "%1"
txtfile="\ProgramData\chocolatey\bin\runemacs.exe"  "%1"
